/*
 * Organization structure API
 * Welcome on the documentation for the Organization Structure API 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AxisSectionTreeless;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AxisSectionAllOf
 */
public class AxisSectionAllOfTest {
    private final AxisSectionAllOf model = new AxisSectionAllOf();

    /**
     * Model tests for AxisSectionAllOf
     */
    @Test
    public void testAxisSectionAllOf() {
        // TODO: test AxisSectionAllOf
    }

    /**
     * Test the property 'parentAxisSections'
     */
    @Test
    public void parentAxisSectionsTest() {
        // TODO: test parentAxisSections
    }

    /**
     * Test the property 'childrenAxisSections'
     */
    @Test
    public void childrenAxisSectionsTest() {
        // TODO: test childrenAxisSections
    }

}
