/*
 * Organization structure API
 * Welcome on the documentation for the Organization Structure API 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AxisTreeless;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Axis
 */
public class AxisTest {
    private final Axis model = new Axis();

    /**
     * Model tests for Axis
     */
    @Test
    public void testAxis() {
        // TODO: test Axis
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'multilingualName'
     */
    @Test
    public void multilingualNameTest() {
        // TODO: test multilingualName
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'parentAxisId'
     */
    @Test
    public void parentAxisIdTest() {
        // TODO: test parentAxisId
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'isReadOnly'
     */
    @Test
    public void isReadOnlyTest() {
        // TODO: test isReadOnly
    }

    /**
     * Test the property 'isNNRelation'
     */
    @Test
    public void isNNRelationTest() {
        // TODO: test isNNRelation
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'parentAxis'
     */
    @Test
    public void parentAxisTest() {
        // TODO: test parentAxis
    }

    /**
     * Test the property 'childrenAxes'
     */
    @Test
    public void childrenAxesTest() {
        // TODO: test childrenAxes
    }

}
