/*
 * Organization structure API
 * Welcome on the documentation for the Organization Structure API 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AxisTreeless;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AxisAllOf
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AxisAllOf {
  public static final String SERIALIZED_NAME_PARENT_AXIS = "parentAxis";
  @SerializedName(SERIALIZED_NAME_PARENT_AXIS)
  private AxisTreeless parentAxis;

  public static final String SERIALIZED_NAME_CHILDREN_AXES = "childrenAxes";
  @SerializedName(SERIALIZED_NAME_CHILDREN_AXES)
  private List<AxisTreeless> childrenAxes = null;

  public AxisAllOf() {
  }

  
  public AxisAllOf(
     List<AxisTreeless> childrenAxes
  ) {
    this();
    this.childrenAxes = childrenAxes;
  }

  public AxisAllOf parentAxis(AxisTreeless parentAxis) {
    
    
    
    
    this.parentAxis = parentAxis;
    return this;
  }

   /**
   * Get parentAxis
   * @return parentAxis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AxisTreeless getParentAxis() {
    return parentAxis;
  }


  public void setParentAxis(AxisTreeless parentAxis) {
    
    
    
    this.parentAxis = parentAxis;
  }


   /**
   * Get childrenAxes
   * @return childrenAxes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AxisTreeless> getChildrenAxes() {
    return childrenAxes;
  }



  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AxisAllOf instance itself
   */
  public AxisAllOf putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AxisAllOf axisAllOf = (AxisAllOf) o;
    return Objects.equals(this.parentAxis, axisAllOf.parentAxis) &&
        Objects.equals(this.childrenAxes, axisAllOf.childrenAxes)&&
        Objects.equals(this.additionalProperties, axisAllOf.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parentAxis, childrenAxes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AxisAllOf {\n");
    sb.append("    parentAxis: ").append(toIndentedString(parentAxis)).append("\n");
    sb.append("    childrenAxes: ").append(toIndentedString(childrenAxes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("parentAxis");
    openapiFields.add("childrenAxes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AxisAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AxisAllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AxisAllOf is not found in the empty JSON string", AxisAllOf.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `parentAxis`
      if (jsonObj.get("parentAxis") != null && !jsonObj.get("parentAxis").isJsonNull()) {
        AxisTreeless.validateJsonObject(jsonObj.getAsJsonObject("parentAxis"));
      }
      if (jsonObj.get("childrenAxes") != null && !jsonObj.get("childrenAxes").isJsonNull()) {
        JsonArray jsonArraychildrenAxes = jsonObj.getAsJsonArray("childrenAxes");
        if (jsonArraychildrenAxes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("childrenAxes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `childrenAxes` to be an array in the JSON string but got `%s`", jsonObj.get("childrenAxes").toString()));
          }

          // validate the optional field `childrenAxes` (array)
          for (int i = 0; i < jsonArraychildrenAxes.size(); i++) {
            AxisTreeless.validateJsonObject(jsonArraychildrenAxes.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AxisAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AxisAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AxisAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AxisAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<AxisAllOf>() {
           @Override
           public void write(JsonWriter out, AxisAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AxisAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AxisAllOf instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AxisAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AxisAllOf
  * @throws IOException if the JSON string is invalid with respect to AxisAllOf
  */
  public static AxisAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AxisAllOf.class);
  }

 /**
  * Convert an instance of AxisAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

