/*
 * Organization structure API
 * Welcome on the documentation for the Organization Structure API 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AxisSectionTreeless;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AxisSectionAllOf
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AxisSectionAllOf {
  public static final String SERIALIZED_NAME_PARENT_AXIS_SECTIONS = "parentAxisSections";
  @SerializedName(SERIALIZED_NAME_PARENT_AXIS_SECTIONS)
  private List<AxisSectionTreeless> parentAxisSections = null;

  public static final String SERIALIZED_NAME_CHILDREN_AXIS_SECTIONS = "childrenAxisSections";
  @SerializedName(SERIALIZED_NAME_CHILDREN_AXIS_SECTIONS)
  private List<AxisSectionTreeless> childrenAxisSections = null;

  public AxisSectionAllOf() {
  }

  public AxisSectionAllOf parentAxisSections(List<AxisSectionTreeless> parentAxisSections) {
    
    
    
    
    this.parentAxisSections = parentAxisSections;
    return this;
  }

  public AxisSectionAllOf addParentAxisSectionsItem(AxisSectionTreeless parentAxisSectionsItem) {
    if (this.parentAxisSections == null) {
      this.parentAxisSections = new ArrayList<>();
    }
    this.parentAxisSections.add(parentAxisSectionsItem);
    return this;
  }

   /**
   * Get parentAxisSections
   * @return parentAxisSections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AxisSectionTreeless> getParentAxisSections() {
    return parentAxisSections;
  }


  public void setParentAxisSections(List<AxisSectionTreeless> parentAxisSections) {
    
    
    
    this.parentAxisSections = parentAxisSections;
  }


  public AxisSectionAllOf childrenAxisSections(List<AxisSectionTreeless> childrenAxisSections) {
    
    
    
    
    this.childrenAxisSections = childrenAxisSections;
    return this;
  }

  public AxisSectionAllOf addChildrenAxisSectionsItem(AxisSectionTreeless childrenAxisSectionsItem) {
    if (this.childrenAxisSections == null) {
      this.childrenAxisSections = new ArrayList<>();
    }
    this.childrenAxisSections.add(childrenAxisSectionsItem);
    return this;
  }

   /**
   * Get childrenAxisSections
   * @return childrenAxisSections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AxisSectionTreeless> getChildrenAxisSections() {
    return childrenAxisSections;
  }


  public void setChildrenAxisSections(List<AxisSectionTreeless> childrenAxisSections) {
    
    
    
    this.childrenAxisSections = childrenAxisSections;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AxisSectionAllOf instance itself
   */
  public AxisSectionAllOf putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AxisSectionAllOf axisSectionAllOf = (AxisSectionAllOf) o;
    return Objects.equals(this.parentAxisSections, axisSectionAllOf.parentAxisSections) &&
        Objects.equals(this.childrenAxisSections, axisSectionAllOf.childrenAxisSections)&&
        Objects.equals(this.additionalProperties, axisSectionAllOf.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parentAxisSections, childrenAxisSections, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AxisSectionAllOf {\n");
    sb.append("    parentAxisSections: ").append(toIndentedString(parentAxisSections)).append("\n");
    sb.append("    childrenAxisSections: ").append(toIndentedString(childrenAxisSections)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("parentAxisSections");
    openapiFields.add("childrenAxisSections");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AxisSectionAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AxisSectionAllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AxisSectionAllOf is not found in the empty JSON string", AxisSectionAllOf.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("parentAxisSections") != null && !jsonObj.get("parentAxisSections").isJsonNull()) {
        JsonArray jsonArrayparentAxisSections = jsonObj.getAsJsonArray("parentAxisSections");
        if (jsonArrayparentAxisSections != null) {
          // ensure the json data is an array
          if (!jsonObj.get("parentAxisSections").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `parentAxisSections` to be an array in the JSON string but got `%s`", jsonObj.get("parentAxisSections").toString()));
          }

          // validate the optional field `parentAxisSections` (array)
          for (int i = 0; i < jsonArrayparentAxisSections.size(); i++) {
            AxisSectionTreeless.validateJsonObject(jsonArrayparentAxisSections.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("childrenAxisSections") != null && !jsonObj.get("childrenAxisSections").isJsonNull()) {
        JsonArray jsonArraychildrenAxisSections = jsonObj.getAsJsonArray("childrenAxisSections");
        if (jsonArraychildrenAxisSections != null) {
          // ensure the json data is an array
          if (!jsonObj.get("childrenAxisSections").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `childrenAxisSections` to be an array in the JSON string but got `%s`", jsonObj.get("childrenAxisSections").toString()));
          }

          // validate the optional field `childrenAxisSections` (array)
          for (int i = 0; i < jsonArraychildrenAxisSections.size(); i++) {
            AxisSectionTreeless.validateJsonObject(jsonArraychildrenAxisSections.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AxisSectionAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AxisSectionAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AxisSectionAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AxisSectionAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<AxisSectionAllOf>() {
           @Override
           public void write(JsonWriter out, AxisSectionAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AxisSectionAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AxisSectionAllOf instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AxisSectionAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AxisSectionAllOf
  * @throws IOException if the JSON string is invalid with respect to AxisSectionAllOf
  */
  public static AxisSectionAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AxisSectionAllOf.class);
  }

 /**
  * Convert an instance of AxisSectionAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

